INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10001,'smk',current_date());
INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10002,'smk1',current_date());
INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10003,'smk2',current_date());