INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10001,'smk',current_date());
INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10002,'smk1',current_date());
INSERT INTO USER_DETAILS (ID,NAME, BIRTH_DATE ) VALUES (10003,'smk2',current_date());

INSERT INTO POST (ID,USER_ID, DESCRIPTION ) VALUES (20001,10001,'I WANT TO LEARN AWS');
INSERT INTO POST (ID,USER_ID, DESCRIPTION ) VALUES (20002,10002,'I WANT TO LEARN AZURE');
INSERT INTO POST (ID,USER_ID, DESCRIPTION ) VALUES (20003,10003,'I WANT TO LEARN GCP');
